name: ytsync
description: "YTSS' most valuable announcement publishing application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0-323.0.dev <3.8.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: 2.2.2 
  crypto: ^3.0.6
  convert: ^3.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_functions: ^5.3.4
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.5
  timer_button: ^2.3.1
  animate_gradient: ^0.0.3
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1  

flutter:
  assets:
    - assets/logo.png
    - assets/plus.png
    - assets/gear.png
    - assets/filter.png
    - assets/plusdark.png
    - assets/geardark.png
    - assets/filterdark.png
  uses-material-design: true
  fonts:
    - family: Pirata One
      fonts:
        - asset: fonts/pirataone.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: ytlogonew
      fonts:
        - asset: fonts/RussoOne-Regular.ttf
    - family: instruct
      fonts:
        - asset: fonts/Prompt-Regular.ttf
    - family: montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf